package employee

type ServiceGroup struct {
	WcStaffEmploymentApplicationService
	WcStaffPassApplicationService
	WcStaffAjustlevelApplicationService
	WcStaffTransferApplicationService
	WcStaffLeaveApplicationService
}
