package employee

type ServiceGroup struct {
	WcStaffEmploymentApplicationService
	WcStaffPassApplicationService
	WcStaffAdjustlevelApplicationService
	WcStaffTransferApplicationService
	WcStaffLeaveApplicationService
}
