package employee

type RouterGroup struct {
	WcStaffEmploymentApplicationRouter
	WcStaffPassApplicationRouter
	WcStaffAdjustlevelApplicationRouter
	WcStaffTransferApplicationRouter
	WcStaffLeaveApplicationRouter
}
