package employee

type RouterGroup struct {
	WcStaffEmploymentApplicationRouter
	WcStaffPassApplicationRouter
	WcStaffAjustlevelApplicationRouter
	WcStaffTransferApplicationRouter
	WcStaffLeaveApplicationRouter
}
